### ISSUE TITLE
[Feature] Support for new microbatching incremental strategy

### ISSUE THREAD

**Issue by jessedobbelaere** [dbt-labs/dbt-athena#715]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature

### Describe the feature

Previously, for large time-series models we needed a custom `insert-by-period` macro. In [this post](https://github.com/dbt-labs/dbt-core/discussions/10672) dbt announced support for the "microbatching" strategy coming to dbt-core 1.9. 

This issue is a placeholder to start preparing for the dbt 1.9 release with this new incremental strategy. Work can be tracked in this epic https://github.com/dbt-labs/dbt-core/issues/10624

### Who will this benefit?

Datasets that are too big to run on initial full load without batching (Athena query times out)

### Anything else?

Closes #190 and probably #697

**Comment by nicor88** [comment]
@amychen1776 the reason why this issue was closed is not clear. Even if dbt Labs is planning to ship such feature, a public open issue could be still relevant to have to track the work that is planned around the adapter - this is valid for any open source code-base, issues are a way to track planned work, or simply to understand relevant features to prioritize by the maintainers.

I recommend therefore to re-open the issue, and eventually leave a clear message that this feature will be shipped by dbt Labs somewhen.

**Comment by amychen1776** [comment]
@nicor88 that's correct - I closed this because this work is being done and tracked in the other issue (and I want to limit duplication)

**Comment by nicor88** [comment]
@amychen1776 could we aim to cross reference issues next time? this microbatch issue is linked in few conversation with the community, and it's good to have a track on what is going on.
Thanks
